version: "3"

services:
    my-app1:
        container_name: my-app
        image: nginx:latest
        restart_policy:
            condition: on-failure
            max_attempts: 5
            restart: always
    my-app2:
        container_name: my-app
        image: nginx:latest
        restart_policy:
            condition: on-failure
            max_attempts: 6
    my-app3:
        restart_policy:
            condition: always

    my-app4:
        container_name: my-app
        image: nginx:latest
        restart_policy:
            condition: no    
