version: "3"

services:
    my-app1:
        container_name: my-app1
        image: nginx:latest
        restart: "on-failure"
    my-app2:
        container_name: my-app2
        image: nginx:latest
        restart: "on-failure"
    my-app3:
        container_name: my-app3
        image: nginx:latest
        restart: "always"

    my-app4:
        container_name: my-app4
        image: nginx:latest
        restart: "no"   
